name: letseedudes
favicon: null
layout_spectrum: 0.18476263037882745
typography_spectrum: 0.10946465120650828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.055012788623571396
  lightness: 0.190519651863724
  saturation: 0.13114737579599023
  rhythmicContrast: 0.2653189771808684
purpose: []
